# define el usuario que ejecuta el proceso de nginx
user nginx;
# Configura el número de procesos de trabajo auto(en función de los núcleos CPU)
worker_processes auto;
# Especifica el archivo de registro de errores y el PID del proceso
error_log /var/log/nginx/error.log;
pid /var/run/nginx.pid;

events {
    # numero máxio de conexiones simultáneas
	worker_connections 1024;
}

http {
    # Habilita una caché compartida de 10MB para sesiones SSL
    ssl_session_cache shared:SSL:10m;
    
    # Establece un tiempo de expiración de 15 minutos para las sesiones SSL
    ssl_session_timeout 15m;

    # Activa los tickets de sesión SSL(reducir la carga del servidor)
    ssl_session_tickets on;

    # Define un grupo de servidores backend llamado "backend_algarza04".
    # Serán los servidores controlados por el balanceador de carga
    upstream backend_algarza04 {
    	server 192.168.10.2;
        server 192.168.10.3;
        server 192.168.10.4;
        server 192.168.10.5;
        server 192.168.10.6;
        server 192.168.10.7;
        server 192.168.10.8;
        server 192.168.10.9;
    }

    server{
        # escucha en el puerto 80
        listen 80;
        server_name nginx_algarza04;

        # manda los mensajes de error y de acceso al log
        access_log /var/log/nginx/nginx_algarza04.access.log;
        error_log /var/log/nginx/nginx_algarza04.error.log;
        location / {
            proxy_pass http://backend_algarza04;
            proxy_set_header Cookie $http_cookie;
            proxy_hide_header Set-Cookie;
        }
        location /estadisticas_algarza04 {
            stub_status on;
        }
    }

    server {
        # escucha en el puerto 443, soporta SSL y HTTP/2
        listen 443 ssl http2;

        # Especifica la ubicación del certificado SSL y su clave privada
        ssl_certificate /etc/nginx/ssl/certificado_algarza04.crt;
        ssl_certificate_key /etc/nginx/ssl/certificado_algarza04.key;

        # Define los protocolos seguros habilitados (TLS 1.2 y TLS 1.3).
        ssl_protocols TLSv1.2 TLSv1.3;

        # Solo las suites más seguras y eficientes
        ssl_ciphers 'TLS_AES_256_GCM_SHA384:TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384';

        # Prioridad a las suites definidas por el servidor
        ssl_prefer_server_ciphers on;



        location / {
            # Redirige las solicitudes al grupo de servidores creado anteriormente
            proxy_pass http://backend_algarza04;
            
            # reenvia las cookies y oculta el encabezado de la cookie
            proxy_set_header Cookie $http_cookie;
            proxy_hide_header Set-Cookie;
        }
    }
}
