
all:
	@echo Los algoritmos se ejecutan como "./1.bin"
	@g++ 1.cpp -o 1.bin -std=c++11 -lstdc++
	@g++ -o 2.bin 2.cpp -std=c++11
	@g++ -o 3.bin 3.cpp -std=c++11
	@g++ -o 4.bin 4.cpp -std=c++11
	@g++ -o 5.bin 5.cpp -std=c++11
	
