# Definimos el VirtualHost que escuchará en el puerto 443
<VirtualHost *:443>

    # Directorio raíz donde se encuentran los archivos que se van a servir
    DocumentRoot /var/www/html

    # Activamos SSL
    SSLEngine on 

    # Indicamos donde se encuentra el SSL público
    SSLCertificateFile /etc/apache2/ssl/certificado_algarza04.crt

    # Indicamos donde se encuentra la clave privada
    SSLCertificateKeyFile /etc/apache2/ssl/certificado_algarza04.key

	# Protocolos seguros
	SSLProtocol -all +TLSv1.2 +TLSv1.3

	# Suites de cifrado fuertes y seguras
	SSLCipherSuite HIGH:!aNULL:!MD5:!RC4:!3DES:!NULL:!EXP:!LOW

	# Es el servidor el que elige los cifrados y no el cliente
	SSLHonorCipherOrder on
</VirtualHost>
